name: build api

on: 
  push:
    branches:
      - main
      - develop
    paths:
      - "api/**"
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - develop
    paths:
      - "api/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: disaply content
         run: |
            cat api/api.txt
       - name: run on main branch
         run: |
            echo "Building main branch"
      
       - name: run on develop branch
         run: |
            echo "Building develop branch"
