name: build api

on: 
  push:
    branches:
      - main
    paths:
      - "api/**"
  pull_request:
    types: [opened, synchronize, reopened ]
    branches:
      - 'main'
      - 'develop'
      - 'master'
    paths:
      - 'api/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: disaply content
         run: |
            cat api/api.txt
