name: pre-release-please

on:
  workflow_dispatch:
      
jobs:
  pre-release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          monorepo-tags: true
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          prerelease: beta
