name: api pre release

on:
  workflow_dispatch:

jobs:
  pre-release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: ${{ secrets.RELEASE_PLEASE_PAT }}
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            api/**
           