name: pre-release-please

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          release-type: simple
          monorepo-tags: true
          token: ${{ secrets.RELEASE_PLEASE_PAT }}     
          prerelease: true     
