name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".release-please-manifest.json"
      
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          monorepo-tags: true
          token: ${{ secrets.RELEASE_PLEASE_PAT }}
          
      - name: print outputs
        run: |
          echo ${{toJSON(steps.release.outputs)}}


