name: test

on: workflow_dispatch:

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [
                  {"field1":"banana", "field2":"kiwi", "field3":"orange"}, 
                  {"field1":"sushi", "field2":"french tacos", "field3":"paracetamol"}
                 ]
    steps:
      - run: echo ${{ matrix.version.0.field1 }}
